### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by bradrice** [smnbbrv/ngx-plyr#43] opened 2020-05-20 16:12 UTC
After running a npm update, my Plyr gets updated to 3.6.2 and I now get this error:

```
ERROR in node_modules/ngx-plyr/lib/plyr-driver/plyr-driver.d.ts(1,8): error TS1192: Module '"<local path>/node_modules/plyr/src/js/plyr"' has no default export.
    node_modules/ngx-plyr/lib/plyr/plyr.component.d.ts(2,8): error TS1192: Module '"<local path>/node_modules/plyr/src/js/plyr"' has no default export.
```
The compiler does compile but with those errors. If I look at plyr/src/js/plyr I do see a default export, so my question is, why isn't the ngx-plyr dpyr-driver.d.ts and plyr.component.d.ts recognizing them?

If I upgrade ngx-plyr to 4.0 I get these errors when I build:

```
ERROR in node_modules/ngx-plyr/lib/plyr/plyr.component.d.ts(9,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/ngx-plyr/lib/plyr/plyr.component.d.ts(65,17): error TS1086: An accessor cannot be declared in an ambient context.
```

Everything works well in modern browsers, I'm working on a web app that has to be compatible back to IE 11 and I just can't seem to get the plyr to work. I see it working on your demo page.

**Comment by smnbbrv** [comment] 2020-05-23 04:53
Duplicate of #38

**Closed by smnbbrv** 2020-05-23 04:53 UTC
