### ISSUE TITLE
Mobile devices

### ISSUE THREAD

**Issue by iovanefelice** [smnbbrv/ngx-plyr#8] opened 2019-04-08 11:23 UTC
The component doesn't work for mobile devices. 
¿Someone else is having the same problem?
When i run my app over a PC i don't have any problems, when i try to use it on a mobile device (ios and android tested) the component never play anything.

My source is a radio streaming url.

Hope anyone could help.

Kind regards,

**Comment by smnbbrv** [comment] 2019-04-08 12:03
Hi @iovanefelice 

could you provide an example?

**Comment by iovanefelice** [comment] 2019-04-08 13:30
Hello Simon,

Yes, i have this app -> http://mradioapp.herokuapp.com/login   credentials are:

username: user
password: password

Once you get in you have to press on "Los 40 principales - Espana" and at the bottom of the page you will see the plyr component displayed.

If press play the streaming starts playing with no problem but if you try to do it on a mobile device the audio is never played.

Heres my .html player tag:

`<div plyr plyrType="audio" [plyrSources]="c.url"></div>`

My app is a radio streaming player, so my c.url attribute is the direct streaming url.

I also imported the plyr module to my app module.

Hope you can help,

Kind regards,
Felix.

**Comment by smnbbrv** [comment] 2019-04-08 13:42
It does not play on my chrome as well:

![image](https://user-images.githubusercontent.com/13453858/55728655-c73cb100-5a14-11e9-99a4-19b38da7ec4d.png)

**Comment by iovanefelice** [comment] 2019-04-08 13:50
I was able to play because i turn off the cors validation.

With the regular HTML5 <audio> tag i can play the source perfectly on any device, why i cant do that with this component?

Hope you can help,

Kind regards,
Felix.

**Comment by smnbbrv** [comment] 2019-04-08 14:01
That's actually interesting. Do you use `crossorigin` on the `audio` tag?

**Comment by smnbbrv** [comment] 2019-04-08 14:07
Would you be able to make it work here with a bare bone plyr? 

https://codepen.io/pen?template=bKeqpr

**Comment by iovanefelice** [comment] 2019-04-08 14:49
Hello Simon,

Yes, if i change the video tag for the audio tag in JS an HTML it doesnt work neather.

With this source i have problems: http://194.169.201.177:8085/Los40
Trying with another one and it works: http://20073.live.streamtheworld.com/CADENASER.mp3

If you open both directly on chrome you will see the default HTML audio tag and it works, but not on this component!!

Any idea? i like this component so much.

Kind regards,
Felix.

**Comment by smnbbrv** [comment] 2019-04-08 15:59
I’d love to further debug it but I would need a stackblitz that fully reproduces the issue: it works on desktop but not on mobile. Just a really simple code with a reproduction

**Comment by smnbbrv** [comment] 2019-04-28 15:38
closing as long as the issue is not really localizable. Please reopen it if you can provide a pure stackblitz example of the problem

**Closed by smnbbrv** 2019-04-28 15:38 UTC

**Comment by anaganisk** [comment] 2019-07-24 12:51
crossorigin attribute is being automatically added which is likely breaking this
